export interface Country {
    eng: string,
    spa: string,
    prefix: string
}
export const COUNTRIES: Country[] = [

  { eng: 'Argentina', spa: 'Argentina', prefix: '+54' },
  { eng: 'Armenia', spa: 'Armenia', prefix: '+374' },
  { eng: 'Aruba', spa: 'Aruba', prefix: '+297' },
  { eng: 'Australia', spa: 'Australia', prefix: '+61' },
  { eng: 'Austria', spa: 'Austria', prefix: '+43' },
  { eng: 'Azerbaijan', spa: 'Azerbaiyán', prefix: '+994' },
  { eng: 'Bahamas', spa: 'Bahamas', prefix: '+1242' },
  { eng: 'Bahrain', spa: 'Bahrein', prefix: '+973' },
  { eng: 'Bangladesh', spa: 'Bangladesh', prefix: '+880' },
  { eng: 'Barbados', spa: 'Barbados', prefix: '+1246' },
  { eng: 'Belarus', spa: 'Bielorrusia', prefix: '+375' },
  { eng: 'Belgium', spa: 'Bélgica', prefix: '+32' },
  { eng: 'Belize', spa: 'Belice', prefix: '+501' },
  { eng: 'Benin', spa: 'Benín', prefix: '+229' },
  { eng: 'Bermuda', spa: 'Bermudas', prefix: '+1441' },
  { eng: 'Bhutan', spa: 'Bután', prefix: '+975' },
  { eng: 'Bolivia', spa: 'Bolivia', prefix: '+591' },
  {
    eng: 'Bosnia and Herzegovina',
    spa: 'Bosnia y Herzegovina',
    prefix: '+387',
  },
  { eng: 'Botswana', spa: 'Botswana', prefix: '+267' },
  { eng: 'Bouvet Island', spa: 'Isla Bouvet', prefix: '+47' },
  { eng: 'Brazil', spa: 'Brasil', prefix: '+55' },
  {
    eng: 'British Indian Ocean Territory',
    spa: 'Territorio Británico del Océano Índico',
    prefix: '+246',
  },
  {
    eng: 'British Virgin Islands',
    spa: 'Islas Vírgenes del Reino Unido',
    prefix: '+1284',
  },
  { eng: 'Brunei', spa: 'Brunei', prefix: '+673' },
  { eng: 'Bulgaria', spa: 'Bulgaria', prefix: '+359' },
  { eng: 'Burkina Faso', spa: 'Burkina Faso', prefix: '+226' },
  { eng: 'Burundi', spa: 'Burundi', prefix: '+257' },
  { eng: 'Cambodia', spa: 'Camboya', prefix: '+855' },
  { eng: 'Cameroon', spa: 'Camerún', prefix: '+237' },
  { eng: 'Canada', spa: 'Canadá', prefix: '+1' },
  { eng: 'Cape Verde', spa: 'Cabo Verde', prefix: '+238' },
  {
    eng: 'Caribbean Netherlands',
    spa: 'Caribe Neerlandés',
    prefix: '+599',
  },
  { eng: 'Cayman Islands', spa: 'Islas Caimán', prefix: '+1345' },
  {
    eng: 'Central African Republic',
    spa: 'República Centroafricana',
    prefix: '+236',
  },
  { eng: 'Chad', spa: 'Chad', prefix: '+235' },
  { eng: 'Chile', spa: 'Chile', prefix: '+56' },
  { eng: 'China', spa: 'China', prefix: '+86' },
  { eng: 'Christmas Island', spa: 'Isla de Navidad', prefix: '+61' },
  {
    eng: 'Cocos (Keeling) Islands',
    spa: 'Islas Cocos o Islas Keeling',
    prefix: '+61',
  },
  { eng: 'Colombia', spa: 'Colombia', prefix: '+57' },
  { eng: 'Comoros', spa: 'Comoras', prefix: '+269' },
  { eng: 'Cook Islands', spa: 'Islas Cook', prefix: '+682' },
  { eng: 'Costa Rica', spa: 'Costa Rica', prefix: '+506' },
  { eng: 'Croatia', spa: 'Croacia', prefix: '+385' },
  { eng: 'Cuba', spa: 'Cuba', prefix: '+53' },
  { eng: 'Curaçao', spa: 'Curazao', prefix: '+599' },
  { eng: 'Cyprus', spa: 'Chipre', prefix: '+357' },
  { eng: 'Czechia', spa: 'Chequia', prefix: '+420' },
  { eng: 'DR Congo', spa: 'Congo (Rep. Dem.)', prefix: '+243' },
  { eng: 'Denmark', spa: 'Dinamarca', prefix: '+45' },
  { eng: 'Djibouti', spa: 'Djibouti', prefix: '+253' },
  { eng: 'Dominica', spa: 'Dominica', prefix: '+1767' },
  {
    eng: 'Dominican Republic',
    spa: 'República Dominicana',
    prefix: '+1809',
  },
  { eng: 'Ecuador', spa: 'Ecuador', prefix: '+593' },
  { eng: 'Egypt', spa: 'Egipto', prefix: '+20' },
  { eng: 'El Salvador', spa: 'El Salvador', prefix: '+503' },
  { eng: 'Equatorial Guinea', spa: 'Guinea Ecuatorial', prefix: '+240' },
  { eng: 'Eritrea', spa: 'Eritrea', prefix: '+291' },
  { eng: 'Estonia', spa: 'Estonia', prefix: '+372' },
  { eng: 'Eswatini', spa: 'Suazilandia', prefix: '+268' },
  { eng: 'Ethiopia', spa: 'Etiopía', prefix: '+251' },
  { eng: 'Falkland Islands', spa: 'Islas Malvinas', prefix: '+500' },
  { eng: 'Faroe Islands', spa: 'Islas Faroe', prefix: '+298' },
  { eng: 'Fiji', spa: 'Fiyi', prefix: '+679' },
  { eng: 'Finland', spa: 'Finlandia', prefix: '+358' },
  { eng: 'France', spa: 'Francia', prefix: '+33' },
  { eng: 'French Guiana', spa: 'Guayana Francesa', prefix: '+594' },
  { eng: 'French Polynesia', spa: 'Polinesia Francesa', prefix: '+689' },
  {
    eng: 'French Southern and Antarctic Lands',
    spa: 'Tierras Australes y Antárticas Francesas',
    prefix: '+262',
  },
  { eng: 'Gabon', spa: 'Gabón', prefix: '+241' },
  { eng: 'Gambia', spa: 'Gambia', prefix: '+220' },
  { eng: 'Georgia', spa: 'Georgia', prefix: '+995' },
  { eng: 'Germany', spa: 'Alemania', prefix: '+49' },
  { eng: 'Ghana', spa: 'Ghana', prefix: '+233' },
  { eng: 'Gibraltar', spa: 'Gibraltar', prefix: '+350' },
  { eng: 'Greece', spa: 'Grecia', prefix: '+30' },
  { eng: 'Greenland', spa: 'Groenlandia', prefix: '+299' },
  { eng: 'Grenada', spa: 'Grenada', prefix: '+1473' },
  { eng: 'Guadeloupe', spa: 'Guadalupe', prefix: '+590' },
  { eng: 'Guam', spa: 'Guam', prefix: '+1671' },
  { eng: 'Guatemala', spa: 'Guatemala', prefix: '+502' },
  { eng: 'Guernsey', spa: 'Guernsey', prefix: '+44' },
  { eng: 'Guinea', spa: 'Guinea', prefix: '+224' },
  { eng: 'Guinea-Bissau', spa: 'Guinea-Bisáu', prefix: '+245' },
  { eng: 'Guyana', spa: 'Guyana', prefix: '+592' },
  { eng: 'Haiti', spa: 'Haití', prefix: '+509' },
  {
    eng: 'Heard Island and McDonald Islands',
    spa: 'Islas Heard y McDonald',
    prefix: '',
  },
  { eng: 'Honduras', spa: 'Honduras', prefix: '+504' },
  { eng: 'Hong Kong', spa: 'Hong Kong', prefix: '+852' },
  { eng: 'Hungary', spa: 'Hungría', prefix: '+36' },
  { eng: 'Iceland', spa: 'Islandia', prefix: '+354' },
  { eng: 'India', spa: 'India', prefix: '+91' },
  { eng: 'Indonesia', spa: 'Indonesia', prefix: '+62' },
  { eng: 'Iran', spa: 'Iran', prefix: '+98' },
  { eng: 'Iraq', spa: 'Irak', prefix: '+964' },
  { eng: 'Ireland', spa: 'Irlanda', prefix: '+353' },
  { eng: 'Isle of Man', spa: 'Isla de Man', prefix: '+44' },
  { eng: 'Israel', spa: 'Israel', prefix: '+972' },
  { eng: 'Italy', spa: 'Italia', prefix: '+39' },
  { eng: 'Ivory Coast', spa: 'Costa de Marfil', prefix: '+225' },
  { eng: 'Jamaica', spa: 'Jamaica', prefix: '+1876' },
  { eng: 'Japan', spa: 'Japón', prefix: '+81' },
  { eng: 'Jersey', spa: 'Jersey', prefix: '+44' },
  { eng: 'Jordan', spa: 'Jordania', prefix: '+962' },
  { eng: 'Kazakhstan', spa: 'Kazajistán', prefix: '+76' },
  { eng: 'Kenya', spa: 'Kenia', prefix: '+254' },
  { eng: 'Kiribati', spa: 'Kiribati', prefix: '+686' },
  { eng: 'Kosovo', spa: 'Kosovo', prefix: '+383' },
  { eng: 'Kuwait', spa: 'Kuwait', prefix: '+965' },
  { eng: 'Kyrgyzstan', spa: 'Kirguizistán', prefix: '+996' },
  { eng: 'Laos', spa: 'Laos', prefix: '+856' },
  { eng: 'Latvia', spa: 'Letonia', prefix: '+371' },
  { eng: 'Lebanon', spa: 'Líbano', prefix: '+961' },
  { eng: 'Lesotho', spa: 'Lesotho', prefix: '+266' },
  { eng: 'Liberia', spa: 'Liberia', prefix: '+231' },
  { eng: 'Libya', spa: 'Libia', prefix: '+218' },
  { eng: 'Liechtenstein', spa: 'Liechtenstein', prefix: '+423' },
  { eng: 'Lithuania', spa: 'Lituania', prefix: '+370' },
  { eng: 'Luxembourg', spa: 'Luxemburgo', prefix: '+352' },
  { eng: 'Macau', spa: 'Macao', prefix: '+853' },
  { eng: 'Madagascar', spa: 'Madagascar', prefix: '+261' },
  { eng: 'Malawi', spa: 'Malawi', prefix: '+265' },
  { eng: 'Malaysia', spa: 'Malasia', prefix: '+60' },
  { eng: 'Maldives', spa: 'Maldivas', prefix: '+960' },
  { eng: 'Mali', spa: 'Mali', prefix: '+223' },
  { eng: 'Malta', spa: 'Malta', prefix: '+356' },
  { eng: 'Marshall Islands', spa: 'Islas Marshall', prefix: '+692' },
  { eng: 'Martinique', spa: 'Martinica', prefix: '+596' },
  { eng: 'Mauritania', spa: 'Mauritania', prefix: '+222' },
  { eng: 'Mauritius', spa: 'Mauricio', prefix: '+230' },
  { eng: 'Mayotte', spa: 'Mayotte', prefix: '+262' },
  { eng: 'Mexico', spa: 'México', prefix: '+52' },
  { eng: 'Micronesia', spa: 'Micronesia', prefix: '+691' },
  { eng: 'Moldova', spa: 'Moldavia', prefix: '+373' },
  { eng: 'Monaco', spa: 'Mónaco', prefix: '+377' },
  { eng: 'Mongolia', spa: 'Mongolia', prefix: '+976' },
  { eng: 'Montenegro', spa: 'Montenegro', prefix: '+382' },
  { eng: 'Montserrat', spa: 'Montserrat', prefix: '+1664' },
  { eng: 'Morocco', spa: 'Marruecos', prefix: '+212' },
  { eng: 'Mozambique', spa: 'Mozambique', prefix: '+258' },
  { eng: 'Myanmar', spa: 'Myanmar', prefix: '+95' },
  { eng: 'Namibia', spa: 'Namibia', prefix: '+264' },
  { eng: 'Nauru', spa: 'Nauru', prefix: '+674' },
  { eng: 'Nepal', spa: 'Nepal', prefix: '+977' },
  { eng: 'Netherlands', spa: 'Países Bajos', prefix: '+31' },
  { eng: 'New Caledonia', spa: 'Nueva Caledonia', prefix: '+687' },
  { eng: 'New Zealand', spa: 'Nueva Zelanda', prefix: '+64' },
  { eng: 'Nicaragua', spa: 'Nicaragua', prefix: '+505' },
  { eng: 'Niger', spa: 'Níger', prefix: '+227' },
  { eng: 'Nigeria', spa: 'Nigeria', prefix: '+234' },
  { eng: 'Niue', spa: 'Niue', prefix: '+683' },
  { eng: 'Norfolk Island', spa: 'Isla de Norfolk', prefix: '+672' },
  { eng: 'North Korea', spa: 'Corea del Norte', prefix: '+850' },
  { eng: 'North Macedonia', spa: 'Macedonia del Norte', prefix: '+389' },
  {
    eng: 'Northern Mariana Islands',
    spa: 'Islas Marianas del Norte',
    prefix: '+1670',
  },
  { eng: 'Norway', spa: 'Noruega', prefix: '+47' },
  { eng: 'Oman', spa: 'Omán', prefix: '+968' },
  { eng: 'Pakistan', spa: 'Pakistán', prefix: '+92' },
  { eng: 'Palau', spa: 'Palau', prefix: '+680' },
  { eng: 'Palestine', spa: 'Palestina', prefix: '+970' },
  { eng: 'Panama', spa: 'Panamá', prefix: '+507' },
  { eng: 'Papua New Guinea', spa: 'Papúa Nueva Guinea', prefix: '+675' },
  { eng: 'Paraguay', spa: 'Paraguay', prefix: '+595' },
  { eng: 'Peru', spa: 'Perú', prefix: '+51' },
  { eng: 'Philippines', spa: 'Filipinas', prefix: '+63' },
  { eng: 'Pitcairn Islands', spa: 'Islas Pitcairn', prefix: '+64' },
  { eng: 'Poland', spa: 'Polonia', prefix: '+48' },
  { eng: 'Portugal', spa: 'Portugal', prefix: '+351' },
  { eng: 'Puerto Rico', spa: 'Puerto Rico', prefix: '+1787' },
  { eng: 'Qatar', spa: 'Catar', prefix: '+974' },
  { eng: 'Republic of the Congo', spa: 'Congo', prefix: '+242' },
  { eng: 'Romania', spa: 'Rumania', prefix: '+40' },
  { eng: 'Russia', spa: 'Rusia', prefix: '+73' },
  { eng: 'Rwanda', spa: 'Ruanda', prefix: '+250' },
  { eng: 'Réunion', spa: 'Reunión', prefix: '+262' },
  { eng: 'Saint Barthélemy', spa: 'San Bartolomé', prefix: '+590' },
  {
    eng: 'Saint Helena, Ascension and Tristan da Cunha',
    spa: 'Santa Elena, Ascensión y Tristán de Acuña',
    prefix: '+290',
  },
  {
    eng: 'Saint Kitts and Nevis',
    spa: 'San Cristóbal y Nieves',
    prefix: '+1869',
  },
  { eng: 'Saint Lucia', spa: 'Santa Lucía', prefix: '+1758' },
  { eng: 'Saint Martin', spa: 'Saint Martin', prefix: '+590' },
  {
    eng: 'Saint Pierre and Miquelon',
    spa: 'San Pedro y Miquelón',
    prefix: '+508',
  },
  {
    eng: 'Saint Vincent and the Grenadines',
    spa: 'San Vicente y Granadinas',
    prefix: '+1784',
  },
  { eng: 'Samoa', spa: 'Samoa', prefix: '+685' },
  { eng: 'San Marino', spa: 'San Marino', prefix: '+378' },
  { eng: 'Saudi Arabia', spa: 'Arabia Saudí', prefix: '+966' },
  { eng: 'Senegal', spa: 'Senegal', prefix: '+221' },
  { eng: 'Serbia', spa: 'Serbia', prefix: '+381' },
  { eng: 'Seychelles', spa: 'Seychelles', prefix: '+248' },
  { eng: 'Sierra Leone', spa: 'Sierra Leone', prefix: '+232' },
  { eng: 'Singapore', spa: 'Singapur', prefix: '+65' },
  { eng: 'Sint Maarten', spa: 'Sint Maarten', prefix: '+1721' },
  { eng: 'Slovakia', spa: 'República Eslovaca', prefix: '+421' },
  { eng: 'Slovenia', spa: 'Eslovenia', prefix: '+386' },
  { eng: 'Solomon Islands', spa: 'Islas Salomón', prefix: '+677' },
  { eng: 'Somalia', spa: 'Somalia', prefix: '+252' },
  { eng: 'South Africa', spa: 'Sudáfrica', prefix: '+27' },  { eng: 'Afghanistan', spa: 'Afganistán', prefix: '+93' },
  { eng: 'Albania', spa: 'Albania', prefix: '+355' },
  { eng: 'Algeria', spa: 'Argelia', prefix: '+213' },
  { eng: 'American Samoa', spa: 'Samoa Americana', prefix: '+1684' },
  { eng: 'Andorra', spa: 'Andorra', prefix: '+376' },
  { eng: 'Angola', spa: 'Angola', prefix: '+244' },
  { eng: 'Anguilla', spa: 'Anguilla', prefix: '+1264' },
  { eng: 'Antarctica', spa: 'Antártida', prefix: '' },
  {
    eng: 'Antigua and Barbuda',
    spa: 'Antigua y Barbuda',
    prefix: '+1268',
  },
  {
    eng: 'South Georgia',
    spa: 'Islas Georgias del Sur y Sandwich del Sur',
    prefix: '+500',
  },
  { eng: 'South Korea', spa: 'Corea del Sur', prefix: '+82' },
  { eng: 'South Sudan', spa: 'Sudán del Sur', prefix: '+211' },
  { eng: 'Spain', spa: 'España', prefix: '+34' },
  { eng: 'Sri Lanka', spa: 'Sri Lanka', prefix: '+94' },
  { eng: 'Sudan', spa: 'Sudán', prefix: '+249' },
  { eng: 'Surieng', spa: 'Surinam', prefix: '+597' },
  {
    eng: 'Svalbard and Jan Mayen',
    spa: 'Islas Svalbard y Jan Mayen',
    prefix: '+4779',
  },
  { eng: 'Sweden', spa: 'Suecia', prefix: '+46' },
  { eng: 'Switzerland', spa: 'Suiza', prefix: '+41' },
  { eng: 'Syria', spa: 'Siria', prefix: '+963' },
  {
    eng: 'São Tomé and Príncipe',
    spa: 'Santo Tomé y Príncipe',
    prefix: '+239',
  },
  { eng: 'Taiwan', spa: 'Taiwán', prefix: '+886' },
  { eng: 'Tajikistan', spa: 'Tayikistán', prefix: '+992' },
  { eng: 'Tanzania', spa: 'Tanzania', prefix: '+255' },
  { eng: 'Thailand', spa: 'Tailandia', prefix: '+66' },
  { eng: 'Timor-Leste', spa: 'Timor Oriental', prefix: '+670' },
  { eng: 'Togo', spa: 'Togo', prefix: '+228' },
  { eng: 'Tokelau', spa: 'Islas Tokelau', prefix: '+690' },
  { eng: 'Tonga', spa: 'Tonga', prefix: '+676' },
  {
    eng: 'Trinidad and Tobago',
    spa: 'Trinidad y Tobago',
    prefix: '+1868',
  },
  { eng: 'Tunisia', spa: 'Túnez', prefix: '+216' },
  { eng: 'Turkey', spa: 'Turquía', prefix: '+90' },
  { eng: 'Turkmenistan', spa: 'Turkmenistán', prefix: '+993' },
  {
    eng: 'Turks and Caicos Islands',
    spa: 'Islas Turks y Caicos',
    prefix: '+1649',
  },
  { eng: 'Tuvalu', spa: 'Tuvalu', prefix: '+688' },
  { eng: 'Uganda', spa: 'Uganda', prefix: '+256' },
  { eng: 'Ukraine', spa: 'Ucrania', prefix: '+380' },
  {
    eng: 'United Arab Emirates',
    spa: 'Emiratos Árabes Unidos',
    prefix: '+971',
  },
  { eng: 'United Kingdom', spa: 'Reino Unido', prefix: '+44' },
  { eng: 'United States', spa: 'Estados Unidos', prefix: '+1201' },
  {
    eng: 'United States Minor Outlying Islands',
    spa: 'Islas Ultramarinas Menores de Estados Unidos',
    prefix: '+268',
  },
  {
    eng: 'United States Virgin Islands',
    spa: 'Islas Vírgenes de los Estados Unidos',
    prefix: '+1340',
  },
  { eng: 'Uruguay', spa: 'Uruguay', prefix: '+598' },
  { eng: 'Uzbekistan', spa: 'Uzbekistán', prefix: '+998' },
  { eng: 'Vanuatu', spa: 'Vanuatu', prefix: '+678' },
  { eng: 'Vatican City', spa: 'Ciudad del Vaticano', prefix: '+3906698' },
  { eng: 'Venezuela', spa: 'Venezuela', prefix: '+58' },
  { eng: 'Vietnam', spa: 'Vietnam', prefix: '+84' },
  { eng: 'Wallis and Futuna', spa: 'Wallis y Futuna', prefix: '+681' },
  { eng: 'Western Sahara', spa: 'Sahara Occidental', prefix: '+2125288' },
  { eng: 'Yemen', spa: 'Yemen', prefix: '+967' },
  { eng: 'Zambia', spa: 'Zambia', prefix: '+260' },
  { eng: 'Zimbabwe', spa: 'Zimbabue', prefix: '+263' },
  { eng: 'Åland Islands', spa: 'Alandia', prefix: '+35818' },
];
